export default {
  login: "chouweihan",
  id: 31234395,
  node_id: "MDQ6VXNlcjMxMjM0Mzk1",
  avatar_url: "https://avatars.githubusercontent.com/u/31234395?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/chouweihan",
  html_url: "https://github.com/chouweihan",
  followers_url: "https://api.github.com/users/chouweihan/followers",
  following_url: "https://api.github.com/users/chouweihan/following{/other_user}",
  gists_url: "https://api.github.com/users/chouweihan/gists{/gist_id}",
  starred_url: "https://api.github.com/users/chouweihan/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/chouweihan/subscriptions",
  organizations_url: "https://api.github.com/users/chouweihan/orgs",
  repos_url: "https://api.github.com/users/chouweihan/repos",
  events_url: "https://api.github.com/users/chouweihan/events{/privacy}",
  received_events_url: "https://api.github.com/users/chouweihan/received_events",
  type: "User",
  site_admin: false,
  name: "Wei-Han Chou",
  company: "mock company",
  blog: "",
  location: "vancouver",
  email: null,
  hireable: null,
  bio: null,
  twitter_username: null,
  public_repos: 6,
  public_gists: 0,
  followers: 0,
  following: 0,
  created_at: "2017-08-22T05:45:47Z",
  updated_at: "2021-07-13T00:08:09Z"
}
